settings:
  link: "http://www.railstutorial.org/"
  help: "http://www.railstutorial.org/help"
  contact: "https://news.railstutorial.org/contact"
  about: "https://news.railstutorial.org/about"
  book: "http://www.railstutorial.org/book"
  author: "https://www.michaelhartl.com/"
  news: "https://news.railstutorial.org/"
  learn: "https://www.learnenough.com/"
  screencast: "https://screencasts.railstutorial.org/"
  RoR: "https://rubyonrails.org/"
  user:
    username:
      max_length: 50
    email:
      max_length: 255
      regex: !ruby/regexp "/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i"
    password:
      min_length: 6
